---
baseURL: "http://shaochenfeng.com/camunda-cn/"
languageCode: "zh-cn"
title: "Camunda 中文站"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "get-started"
      name: "入门教程"
      url: "https://docs.camunda.org/get-started/"
    - id: "get-started"
      name: "译者的入门教程"
      url: "http://shaochenfeng.com/camunda/"
    - id: "manual"
      name: "Camunda 平台"
      url: "/camunda-cn"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "7.16"
    versions:
      - "develop"
  github:
    repositoryName: "zoollcar/camunda-docs-manual-cn"
    branch: "master"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
